name: Build and Push Docker Image to Harbor

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t registry.cn-heyuan.aliyuncs.com/dockrhub_image/demo_image/my-nginx:latest .

      - name: Tag Docker image for Harbor
        run: |
          docker tag registry.cn-heyuan.aliyuncs.com/dockrhub_image/demo_image/my-nginx:latest registry.cn-heyuan.aliyuncs.com/dockrhub_image/demo_image:0.1

      - name: Login to Harbor
        run: |
          echo ${{ secrets.ALIYUN_PASSWORD }} | docker login registry.cn-heyuan.aliyuncs.com --username ${{ secrets.ALIYUN_USERNAME }} --password-stdin

      - name: Push Docker image to Harbor
        run: |
          docker push registry.cn-heyuan.aliyuncs.com/dockrhub_image/demo_image:0.1
