name: Build and Push Docker Image to Harbor

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check network connectivity
        run: ping -c 5 192.168.120.113
        
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t 192.168.120.113/library/my-nginx:latest .

      - name: Tag Docker image for Harbor
        run: |
          docker tag 192.168.120.113/library/my-nginx:latest 192.168.120.113/library/my-nginx:latest

      - name: Login to Harbor
        run: |
          echo ${{ secrets.HARBOR_PASSWORD }} | docker login 192.168.120.113 --username ${{ secrets.HARBOR_USERNAME }} --password-stdin

      - name: Push Docker image to Harbor
        run: |
          docker push 192.168.120.113/library/my-nginx:latest
